/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import com.Menu;
import dao.Credentials;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import javax.swing.JOptionPane;

/**
 *
 * @author THINKPAD
 */
public class LoginSubPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginSubPanel
     */
//    FormBuku cgui = new FormBuku();
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProjectLimangatusPU");
    EntityManager em = emf.createEntityManager();

    public LoginSubPanel() {
        initComponents();
        focus();
    }

    public void focus() {
        jTextFieldUsername.grabFocus();
    }

    public void addEventRegister(ActionListener actionListener) {
        jButtonDaftar.addActionListener(actionListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonMasuk = new javax.swing.JButton();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jButtonDaftar = new javax.swing.JButton();

        setBackground(new java.awt.Color(171, 213, 171));

        jLabel1.setText("Nama Pengguna");

        jLabel2.setText("Kata Sandi");

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 45, 45));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Masuk");

        jButtonMasuk.setBackground(new java.awt.Color(31, 85, 20));
        jButtonMasuk.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButtonMasuk.setForeground(new java.awt.Color(228, 229, 241));
        jButtonMasuk.setText("Masuk");
        jButtonMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasukActionPerformed(evt);
            }
        });

        jTextFieldUsername.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jTextFieldUsername.setForeground(java.awt.Color.gray);
        jTextFieldUsername.setText("Nama Pengguna...");
        jTextFieldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsernameFocusLost(evt);
            }
        });

        jPasswordFieldPassword.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jPasswordFieldPassword.setForeground(java.awt.Color.gray);
        jPasswordFieldPassword.setText("***********");
        jPasswordFieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldPasswordFocusLost(evt);
            }
        });
        jPasswordFieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldPasswordKeyPressed(evt);
            }
        });

        jButtonDaftar.setBackground(new java.awt.Color(228, 229, 241));
        jButtonDaftar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButtonDaftar.setForeground(new java.awt.Color(31, 85, 20));
        jButtonDaftar.setText("Daftar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jButtonMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldUsername)
                    .addComponent(jPasswordFieldPassword)
                    .addComponent(jButtonDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasukActionPerformed
        // TODO add your handling code here:
        prosesLogin();
    }//GEN-LAST:event_jButtonMasukActionPerformed

    private void jPasswordFieldPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            prosesLogin();
        }
    }//GEN-LAST:event_jPasswordFieldPasswordKeyPressed

    private void jTextFieldUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsernameFocusLost
        // TODO add your handling code here:
        if (jTextFieldUsername.getText().equals("")) {
            jTextFieldUsername.setFont(new Font("Segoe UI Plain", 2, 12));
            jTextFieldUsername.setForeground(Color.gray);
            jTextFieldUsername.setText("Nama Pengguna...");
        }
    }//GEN-LAST:event_jTextFieldUsernameFocusLost

    private void jPasswordFieldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordFocusLost
        // TODO add your handling code here:
        if (jPasswordFieldPassword.getText().equals("")) {
            jPasswordFieldPassword.setFont(new Font("Segoe UI Plain", 2, 12));
            jPasswordFieldPassword.setForeground(Color.gray);
            jPasswordFieldPassword.setText("***********");
        }
    }//GEN-LAST:event_jPasswordFieldPasswordFocusLost

    private void jTextFieldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsernameFocusGained
        // TODO add your handling code here:
        jTextFieldUsername.setFont(new Font("Segoe UI Plain", 0, 12));
        jTextFieldUsername.setForeground(Color.black);
        if (jTextFieldUsername.getText().equals("Nama Pengguna...")) {
            jTextFieldUsername.setText(null);
        }
    }//GEN-LAST:event_jTextFieldUsernameFocusGained

    private void jPasswordFieldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordFocusGained
        // TODO add your handling code here:
        jPasswordFieldPassword.setFont(new Font("Segoe UI Plain", 0, 12));
        jPasswordFieldPassword.setForeground(Color.black);
        if (jPasswordFieldPassword.getText().equals("***********")) {
            jPasswordFieldPassword.setText(null);
        }
    }//GEN-LAST:event_jPasswordFieldPasswordFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDaftar;
    private javax.swing.JButton jButtonMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

    private void prosesLogin() {
        try {
            String username = jTextFieldUsername.getText();
            String password = new String(jPasswordFieldPassword.getPassword());
            em.getTransaction().begin();
            CriteriaBuilder cb = em.getCriteriaBuilder();
            CriteriaQuery<Credentials> cq = cb.createQuery(Credentials.class);
            Root<Credentials> root = cq.from(Credentials.class);
            cq.where(
                    cb.equal(root.get("username"), username),
                    cb.equal(root.get("password"), password)
            );
            TypedQuery<Credentials> q = em.createQuery(cq);
            Credentials cred = q.getSingleResult();
            System.out.println("Login as: " + cred.getUsername());
            JOptionPane.showMessageDialog(this, "Login sebagai " + cred.getRoles());
            if (cred.getRoles().equals("Mahasiswa")) {
                MainMenuMahasiswa mainMenuMahasiswa = new MainMenuMahasiswa(cred.getUsername(), cred.getRoles());
                mainMenuMahasiswa.setVisible(true);
                mainMenuMahasiswa.revalidate();
            } else if (cred.getRoles().equals("Dosen")) {
                MainMenuDosen mainMenuDosen = new MainMenuDosen(cred.getUsername(), cred.getRoles());
                mainMenuDosen.setVisible(true);
                mainMenuDosen.revalidate();
            } else {
                MainMenuAdmin mainMenuAdmin = new MainMenuAdmin(cred.getUsername(), cred.getRoles());
                mainMenuAdmin.setVisible(true);
                mainMenuAdmin.revalidate();
            }

            em.getTransaction().commit();
//            Menu menu = new Menu(cred.getUsername(), cred.getRoles());

//            mainMenu.forwardCred(cred.getUsername(), cred.getRoles());
        } catch (NoResultException e) {
            JOptionPane.showMessageDialog(this, "Nama Pengguna / Kata Sandi Salah!");
            em.getTransaction().commit();
            jTextFieldUsername.setText("");
            jPasswordFieldPassword.setText("");
        }
    }
}
