/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import dao.Credentials;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author THINKPAD
 */
public class RegisterSubPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginSubPanel
     */
    FormBuku cgui = new FormBuku();
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProjectLimangatusPU");
    EntityManager em = emf.createEntityManager();

    public RegisterSubPanel() {
        initComponents();
    }

    public void focus() {
        jTextFieldUsername.grabFocus();
    }

    public void addEventRegister(ActionListener actionListener) {
        jButtonMasuk.addActionListener(actionListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonDaftar = new javax.swing.JButton();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldPasswordConfirm = new javax.swing.JPasswordField();
        jComboBoxRoles = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButtonMasuk = new javax.swing.JButton();

        setBackground(new java.awt.Color(171, 213, 171));

        jLabel1.setText("Kata Sandi");

        jLabel2.setText("Konfirmasi Kata Sandi");

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 45, 45));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Daftar");

        jButtonDaftar.setBackground(new java.awt.Color(31, 85, 20));
        jButtonDaftar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButtonDaftar.setForeground(new java.awt.Color(228, 229, 241));
        jButtonDaftar.setText("Daftar");
        jButtonDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDaftarActionPerformed(evt);
            }
        });

        jPasswordFieldPassword.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jPasswordFieldPassword.setForeground(java.awt.Color.gray);
        jPasswordFieldPassword.setText("***********");
        jPasswordFieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldPasswordFocusLost(evt);
            }
        });

        jTextFieldUsername.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jTextFieldUsername.setForeground(java.awt.Color.gray);
        jTextFieldUsername.setText("Nama Pengguna...");
        jTextFieldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsernameFocusLost(evt);
            }
        });

        jLabel4.setText("Nama Pengguna");

        jPasswordFieldPasswordConfirm.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jPasswordFieldPasswordConfirm.setForeground(java.awt.Color.gray);
        jPasswordFieldPasswordConfirm.setText("***********");
        jPasswordFieldPasswordConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldPasswordConfirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldPasswordConfirmFocusLost(evt);
            }
        });

        jComboBoxRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mahasiswa", "Dosen" }));

        jLabel5.setText("Daftar Sebagai");

        jButtonMasuk.setBackground(new java.awt.Color(228, 229, 241));
        jButtonMasuk.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButtonMasuk.setForeground(new java.awt.Color(31, 85, 20));
        jButtonMasuk.setText("Masuk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jButtonDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldPassword)
                    .addComponent(jTextFieldUsername)
                    .addComponent(jPasswordFieldPasswordConfirm)
                    .addComponent(jComboBoxRoles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jPasswordFieldPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(jComboBoxRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDaftarActionPerformed
        // TODO add your handling code here:

        if (jPasswordFieldPassword.getText().equals(jPasswordFieldPasswordConfirm.getText())) {
            // jika password sama dengan konfirmasi password
            em.getTransaction().begin();
            Credentials simpanCredentials = new Credentials();
            simpanCredentials.setUsername(jTextFieldUsername.getText());
            simpanCredentials.setPassword(new String(jPasswordFieldPassword.getPassword()));
            simpanCredentials.setRoles(jComboBoxRoles.getSelectedItem().toString());
            em.persist(simpanCredentials);
            em.getTransaction().commit();
            JOptionPane.showMessageDialog(null, "Daftar Berhasil");
        } else {
            // jika password beda dengan konfirmasi password
            JOptionPane.showMessageDialog(null, "Password yang diisi berbeda!");
//            cgui.setVisible(true);
//            LoginForm loginForm = (LoginForm) SwingUtilities.windowForComponent(jButtonDaftar);
//            loginForm.dispose();
        }

    }//GEN-LAST:event_jButtonDaftarActionPerformed

    private void jTextFieldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsernameFocusGained
        // TODO add your handling code here:
        jTextFieldUsername.setFont(new Font("Segoe UI Plain", 0, 12));
        jTextFieldUsername.setForeground(Color.black);
        if (jTextFieldUsername.getText().equals("Nama Pengguna...")) {
            jTextFieldUsername.setText(null);
        }
    }//GEN-LAST:event_jTextFieldUsernameFocusGained

    private void jTextFieldUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsernameFocusLost
        // TODO add your handling code here:
        if (jTextFieldUsername.getText().equals("")) {
            jTextFieldUsername.setFont(new Font("Segoe UI Plain", 2, 12));
            jTextFieldUsername.setForeground(Color.gray);
            jTextFieldUsername.setText("Nama Pengguna...");
        }
    }//GEN-LAST:event_jTextFieldUsernameFocusLost

    private void jPasswordFieldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordFocusGained
        // TODO add your handling code here:
        jPasswordFieldPassword.setFont(new Font("Segoe UI Plain", 0, 12));
        jPasswordFieldPassword.setForeground(Color.black);
        if (jPasswordFieldPassword.getText().equals("***********")) {
            jPasswordFieldPassword.setText(null);
        }
    }//GEN-LAST:event_jPasswordFieldPasswordFocusGained

    private void jPasswordFieldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordFocusLost
        // TODO add your handling code here:
        if (jPasswordFieldPassword.getText().equals("")) {
            jPasswordFieldPassword.setFont(new Font("Segoe UI Plain", 2, 12));
            jPasswordFieldPassword.setForeground(Color.gray);
            jPasswordFieldPassword.setText("***********");
        }
    }//GEN-LAST:event_jPasswordFieldPasswordFocusLost

    private void jPasswordFieldPasswordConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordConfirmFocusGained
        // TODO add your handling code here:
        jPasswordFieldPasswordConfirm.setFont(new Font("Segoe UI Plain", 0, 12));
        jPasswordFieldPasswordConfirm.setForeground(Color.black);
        if (jPasswordFieldPasswordConfirm.getText().equals("***********")) {
            jPasswordFieldPasswordConfirm.setText(null);
        }
    }//GEN-LAST:event_jPasswordFieldPasswordConfirmFocusGained

    private void jPasswordFieldPasswordConfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordConfirmFocusLost
        // TODO add your handling code here:
        if (jPasswordFieldPasswordConfirm.getText().equals("")) {
            jPasswordFieldPasswordConfirm.setFont(new Font("Segoe UI Plain", 2, 12));
            jPasswordFieldPasswordConfirm.setForeground(Color.gray);
            jPasswordFieldPasswordConfirm.setText("***********");
        }
    }//GEN-LAST:event_jPasswordFieldPasswordConfirmFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDaftar;
    private javax.swing.JButton jButtonMasuk;
    private javax.swing.JComboBox<String> jComboBoxRoles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JPasswordField jPasswordFieldPasswordConfirm;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

}
