/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import dao.Buku;
import dao.Kategori;
import dao.Mahasiswa;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Join;
import javax.persistence.criteria.JoinType;
import javax.persistence.criteria.Root;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THINKPAD
 */
public class FormHomepage extends javax.swing.JPanel {

    /**
     * Creates new form FormPeminjaman
     */
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProjectLimangatusPU");
    EntityManager em = emf.createEntityManager();
    
    public FormHomepage() {
        initComponents();
        setOpaque(false);
        setTableModel();
        loadData();
        loadCardboxBuku();
        loadCardboxMhs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateTanggalPinjam = new model.DateChooser();
        dateTanggalKembali = new model.DateChooser();
        panelMain = new com.raven.swing.RoundPanel();
        panelView = new com.raven.swing.RoundPanel();
        jLabelDashboard = new javax.swing.JLabel();
        jScrollPaneRiwayatPeminjamanBukuDashboard = new javax.swing.JScrollPane();
        jTableDataRiwayatPeminjamanBukuDashboard = new javax.swing.JTable();
        roundPanelMahasiswa = new com.raven.swing.RoundPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelJumlahMahasiswa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roundPanelBuku = new com.raven.swing.RoundPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelJumlahBuku = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        roundPanelPeminjaman = new com.raven.swing.RoundPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabelJumlaPeminjaman = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        roundPanelMahasiswa7 = new com.raven.swing.RoundPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabelJumlahPengembalian = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabelDashboard1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(55, 55, 55));
        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(55, 55, 55));

        jLabelDashboard.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabelDashboard.setForeground(new java.awt.Color(242, 242, 242));
        jLabelDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/homepage20x20.png"))); // NOI18N
        jLabelDashboard.setText("Homepage");

        jTableDataRiwayatPeminjamanBukuDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneRiwayatPeminjamanBukuDashboard.setViewportView(jTableDataRiwayatPeminjamanBukuDashboard);

        roundPanelMahasiswa.setBackground(new java.awt.Color(228, 229, 241));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 85, 20));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MAHASISWA");

        jLabelJumlahMahasiswa.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabelJumlahMahasiswa.setForeground(new java.awt.Color(25, 163, 55));
        jLabelJumlahMahasiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJumlahMahasiswa.setText("666");

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 163, 55));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mahasiswa48x48.png"))); // NOI18N

        javax.swing.GroupLayout roundPanelMahasiswaLayout = new javax.swing.GroupLayout(roundPanelMahasiswa);
        roundPanelMahasiswa.setLayout(roundPanelMahasiswaLayout);
        roundPanelMahasiswaLayout.setHorizontalGroup(
            roundPanelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelJumlahMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        roundPanelMahasiswaLayout.setVerticalGroup(
            roundPanelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(roundPanelMahasiswaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelJumlahMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        roundPanelBuku.setBackground(new java.awt.Color(228, 229, 241));

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(31, 85, 20));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("BUKU");

        jLabelJumlahBuku.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabelJumlahBuku.setForeground(new java.awt.Color(25, 163, 55));
        jLabelJumlahBuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJumlahBuku.setText("666");

        jLabel15.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(25, 163, 55));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buku48x48.png"))); // NOI18N

        javax.swing.GroupLayout roundPanelBukuLayout = new javax.swing.GroupLayout(roundPanelBuku);
        roundPanelBuku.setLayout(roundPanelBukuLayout);
        roundPanelBukuLayout.setHorizontalGroup(
            roundPanelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelJumlahBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        roundPanelBukuLayout.setVerticalGroup(
            roundPanelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(roundPanelBukuLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelJumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        roundPanelPeminjaman.setBackground(new java.awt.Color(228, 229, 241));

        jLabel16.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(31, 85, 20));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("PEMINJAMAN");

        jLabelJumlaPeminjaman.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabelJumlaPeminjaman.setForeground(new java.awt.Color(25, 163, 55));
        jLabelJumlaPeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJumlaPeminjaman.setText("0");

        jLabel21.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(25, 163, 55));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pinjambuku48x48.png"))); // NOI18N

        javax.swing.GroupLayout roundPanelPeminjamanLayout = new javax.swing.GroupLayout(roundPanelPeminjaman);
        roundPanelPeminjaman.setLayout(roundPanelPeminjamanLayout);
        roundPanelPeminjamanLayout.setHorizontalGroup(
            roundPanelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelPeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelJumlaPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        roundPanelPeminjamanLayout.setVerticalGroup(
            roundPanelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelPeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(roundPanelPeminjamanLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelJumlaPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        roundPanelMahasiswa7.setBackground(new java.awt.Color(228, 229, 241));

        jLabel22.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(31, 85, 20));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("PENGEMBALIAN");

        jLabelJumlahPengembalian.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabelJumlahPengembalian.setForeground(new java.awt.Color(25, 163, 55));
        jLabelJumlahPengembalian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJumlahPengembalian.setText("0");

        jLabel24.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(25, 163, 55));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/kembalibuku48x48.png"))); // NOI18N

        javax.swing.GroupLayout roundPanelMahasiswa7Layout = new javax.swing.GroupLayout(roundPanelMahasiswa7);
        roundPanelMahasiswa7.setLayout(roundPanelMahasiswa7Layout);
        roundPanelMahasiswa7Layout.setHorizontalGroup(
            roundPanelMahasiswa7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelMahasiswa7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanelMahasiswa7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelJumlahPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        roundPanelMahasiswa7Layout.setVerticalGroup(
            roundPanelMahasiswa7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelMahasiswa7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanelMahasiswa7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(roundPanelMahasiswa7Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelJumlahPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabelDashboard1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabelDashboard1.setForeground(new java.awt.Color(242, 242, 242));
        jLabelDashboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/riwayatbuku20x20.png"))); // NOI18N
        jLabelDashboard1.setText("Data Buku Terbaru");

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addComponent(roundPanelMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(roundPanelBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(roundPanelPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roundPanelMahasiswa7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneRiwayatPeminjamanBukuDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDashboard)
                            .addComponent(jLabelDashboard1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDashboard)
                .addGap(18, 18, 18)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundPanelMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundPanelBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundPanelPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundPanelMahasiswa7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelDashboard1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneRiwayatPeminjamanBukuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelMain.add(panelView, "card2");

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private model.DateChooser dateTanggalKembali;
    private model.DateChooser dateTanggalPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDashboard;
    private javax.swing.JLabel jLabelDashboard1;
    private javax.swing.JLabel jLabelJumlaPeminjaman;
    private javax.swing.JLabel jLabelJumlahBuku;
    private javax.swing.JLabel jLabelJumlahMahasiswa;
    private javax.swing.JLabel jLabelJumlahPengembalian;
    private javax.swing.JScrollPane jScrollPaneRiwayatPeminjamanBukuDashboard;
    private javax.swing.JTable jTableDataRiwayatPeminjamanBukuDashboard;
    private com.raven.swing.RoundPanel panelMain;
    private com.raven.swing.RoundPanel panelView;
    private com.raven.swing.RoundPanel roundPanelBuku;
    private com.raven.swing.RoundPanel roundPanelMahasiswa;
    private com.raven.swing.RoundPanel roundPanelMahasiswa7;
    private com.raven.swing.RoundPanel roundPanelPeminjaman;
    // End of variables declaration//GEN-END:variables

    private void getData(DefaultTableModel model) {
        model.setRowCount(0);
        em.getTransaction().begin();

        CriteriaBuilder cb = em.getCriteriaBuilder();
        CriteriaQuery<Object[]> cq = cb.createQuery(Object[].class);

        Root<Buku> bukuRoot = cq.from(Buku.class);
        Join<Buku, Kategori> kategoriJoin = bukuRoot.join("idKategori", JoinType.INNER);

        cq.multiselect(
                bukuRoot.get("isbn"),
                bukuRoot.get("judulBuku"),
                bukuRoot.get("penerbit"),
                bukuRoot.get("tahunTerbit"),
                bukuRoot.get("gambar"),
                kategoriJoin.get("namaKategori")
        );

        TypedQuery<Object[]> query = em.createQuery(cq);
        List<Object[]> resultList = query.getResultList();
        for (Object[] row : resultList) {
            byte[] imageBytes = (byte[]) row[4]; // Assuming the index 4 corresponds to the 'gambar' field
            ImageIcon imageIcon = new ImageIcon(imageBytes);

            model.addRow(new Object[]{
                row[0], // isbn
                row[1], // judulBuku
                row[2], // penerbit
                row[3], // tahunTerbit
                row[5], // kategori
                imageIcon // gambar
            });
        }
        em.getTransaction().commit();
    }

    private void loadData() {
        getData((DefaultTableModel) jTableDataRiwayatPeminjamanBukuDashboard.getModel());
    }

    private void showPanel() {
        panelMain.removeAll();
        panelMain.add(new FormHomepage());
        panelMain.repaint();
        panelMain.revalidate();
    }

    private void getImage() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(new FileNameExtensionFilter("Gambar", "jpg", "png", "jpeg"));
    }

    private void setTableModel() {
//        class MyTabelModel extends DefaultTableModel {
//
//            @Override
//            public Class<?> getColumnClass(int columnIndex) {
//                if (columnIndex == 5) {
//                    return ImageIcon.class;
//                }
//                return super.getColumnClass(columnIndex); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
//            }
//
//            @Override
//            public Object getValueAt(int row, int column) {
//                if (column == 5) {
//                    return data[row][5];
//                }
//                return data[row][column]; // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
//            }
//            
//            
//
//        }
        DefaultTableModel model = (DefaultTableModel) jTableDataRiwayatPeminjamanBukuDashboard.getModel();
        model.setColumnCount(0);
        model.addColumn("ISBN");
        model.addColumn("Judul Buku");
        model.addColumn("Penerbit");
        model.addColumn("Tahun Terbit");
        model.addColumn("Kategori");
        model.addColumn("Gambar");
    }

    private void loadCardboxBuku() {
        em.getTransaction().begin();

        CriteriaBuilder cb = em.getCriteriaBuilder();
        CriteriaQuery<Long> cq = cb.createQuery(Long.class);

        Root<Buku> bukuRoot = cq.from(Buku.class);
        Join<Buku, Kategori> kategoriJoin = bukuRoot.join("idKategori", JoinType.INNER);

        cq.select(cb.count(bukuRoot.get("judulBuku")));
        TypedQuery<Long> query = em.createQuery(cq);
        jLabelJumlahBuku.setText(query.getSingleResult().toString());
        em.getTransaction().commit();
    }
    
        private void loadCardboxMhs() {
        em.getTransaction().begin();

        CriteriaBuilder cb = em.getCriteriaBuilder();
        CriteriaQuery<Long> cq = cb.createQuery(Long.class);

        Root<Mahasiswa> bukuRoot = cq.from(Mahasiswa.class);
//        Join<Buku, Kategori> kategoriJoin = bukuRoot.join("idKategori", JoinType.INNER);adm   adm

        cq.select(cb.count(bukuRoot.get("nim")));
        TypedQuery<Long> query = em.createQuery(cq);
        jLabelJumlahMahasiswa.setText(query.getSingleResult().toString());
        em.getTransaction().commit();
    }

}
